# Generated by Django 5.1.2 on 2025-12-24 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="days_valid",
        ),
        migrations.AddField(
            model_name="client",
            name="validity_seconds",
            field=models.IntegerField(default=31536000),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="client",
            name="secret_key",
            field=models.TextField(),
        ),
    ]
