# Generated by Django 5.1.2 on 2026-01-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0002_remove_client_days_valid_client_validity_seconds_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password_hash", models.CharField(max_length=128)),
            ],
        ),
    ]
