# Generated by Django 5.1.2 on 2026-01-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0003_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        default="BilloFy Admin",
                        help_text="Full project name",
                        max_length=100,
                    ),
                ),
                (
                    "project_name_short",
                    models.CharField(
                        default="BilloFy", help_text="Short project name", max_length=50
                    ),
                ),
                (
                    "logo_path",
                    models.CharField(
                        default="images/billofy_key.png",
                        help_text="Path to logo file in static folder",
                        max_length=255,
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="red", help_text="Primary brand color", max_length=50
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
