# Generated by Django 5.1.2 on 2026-01-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0004_sitesetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Upload a logo image",
                null=True,
                upload_to="logos/",
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="logo_path",
            field=models.CharField(
                default="images/billofy_key.png",
                help_text="Path to logo file in static folder (fallback)",
                max_length=255,
            ),
        ),
    ]
