# Generated by Django 5.1.2 on 2026-01-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0005_sitesetting_logo_alter_sitesetting_logo_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftwareUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="e.g. 1.0.1", max_length=20, unique=True
                    ),
                ),
                ("title", models.CharField(default="New Update", max_length=100)),
                ("description", models.TextField(blank=True)),
                ("update_file", models.FileField(upload_to="updates/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
