# Generated by Django 5.1.2 on 2026-01-06 21:00

import licenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0006_softwareupdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="softwareupdate",
            name="update_file",
            field=models.FileField(upload_to=licenses.models.update_file_path),
        ),
    ]
