# Generated by Django 5.1.2 on 2026-01-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0007_alter_softwareupdate_update_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="hardware_id",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
