# Generated by Django 5.2.10 on 2026-01-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0008_alter_client_hardware_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="softwareupdate",
            name="update_type",
            field=models.CharField(
                choices=[
                    ("optional", "Optional"),
                    ("recommended", "Recommended"),
                    ("critical", "Critical"),
                ],
                default="optional",
                max_length=20,
            ),
        ),
    ]
