# Generated by Django 5.2.10 on 2026-08-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0009_softwareupdate_update_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="github_repo",
            field=models.CharField(
                blank=True,
                default="mohsinalisheliya/billofy-releases",
                help_text="Format: username/repo-name",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="github_token",
            field=models.CharField(
                blank=True,
                help_text="Fine-grained PAT for pushing releases to GitHub",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="github_token_expiry",
            field=models.DateField(
                blank=True,
                help_text="Jab tak token valid hai — dashboard pe warning ke liye",
                null=True,
            ),
        ),
    ]
