# Generated by Django 5.2.10 on 2026-08-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0010_sitesetting_github_repo_sitesetting_github_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="softwareupdate",
            name="download_url",
            field=models.URLField(
                blank=True,
                help_text="GitHub Release asset download URL",
                max_length=500,
                null=True,
            ),
        ),
    ]
