"""
Django settings for key_generation project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-7x*&wn)n=$+lwdd(sp2z+7^fqb#93f&i2=cxnf8mke!8m+jb8a"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'licenses',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "key_generation.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "licenses.context_processors.branding",  # Add branding to all templates
            ],
        },
    },
]

WSGI_APPLICATION = "key_generation.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Add this NEW section to tell Django where your files are
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --- BRANDING CONFIGURATION ---
# Centralized branding settings - change project name and logo from here
BRANDING = {
    'PROJECT_NAME': 'BilloFy Admin',
    'PROJECT_NAME_SHORT': 'BilloFy',
    'LOGO_PATH': 'images/billofy_key.png',
    'PRIMARY_COLOR': 'red',  # For future customization
}

# --- CUSTOM LOGIN SYSTEM SETTINGS ---
MASTER_ADMIN_PASSWORD = "admin"  # <--- SET YOUR PASSWORD HERE

# --- SESSION CONFIGURATION (Robust & Secure) ---
# Use database-backed sessions for reliability and persistence
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Default session duration (24 hours)
# This can be overridden per-user with Remember Me functionality
SESSION_COOKIE_AGE = 86400  # 24 hours in seconds

# Expire session when browser closes (default behavior)
# This is overridden when Remember Me is checked
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Refresh session expiry on every request to keep active users logged in
SESSION_SAVE_EVERY_REQUEST = True

# Security settings for session cookies
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS

# Session cookie name
SESSION_COOKIE_NAME = 'billofy_sessionid'

# --- MEDIA FILES (User Uploads) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'